apiVersion: v1
kind: Service
metadata:
  name: game-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: game-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
